### ISSUE TITLE
Class name got cutted if the name is long

### ISSUE THREAD

**Issue by ayarotskiy** [mikeerickson/phpunit-pretty-result-printer#166] opened 2020-08-27 12:21 UTC
PHPUnit Pretty Result Printer 0.28.0
PHPUnit 9.0.0
Symfony 5.1.3
![Снимок экрана от 2020-08-27 19-19-06](https://user-images.githubusercontent.com/61584154/91441421-5c567900-e89a-11ea-817e-1736e01605f9.png)

Could it be fixed? Maybe throw the option?

**Comment by mikeerickson** [comment] 2020-08-27 16:07
This is by design, we have allocated a maximum of 50 characters for class name length.  We have an internal build we are working on which will make this an option, but for now it is fixed at 50 characters.

**Comment by mikeerickson** [comment] 2020-08-27 16:09
Duplicate https://github.com/mikeerickson/phpunit-pretty-result-printer/issues/144

**Comment by mikeerickson** [comment] 2020-09-13 18:09
Addressed in `0.29.0` release see `cd-printer-dont-format-classname` option in `phpunit-printer.yml` for setting

**Closed by mikeerickson** 2020-09-13 18:09 UTC
Labels: future
